import { Inter } from "next/font/google";
import "./globals.css";
// import Navber from "./components/Navber";
import Footer from "./components/Footer";
import Home from "./home/page";
import Hero from "./components/Hero";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navber></Navber> */}
        {/* <Navber></Navber> */}
        {/* <Hero></Hero> */}
        <Home></Home>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
